import type { ServiceRecord } from "@/types/booking";

export const DEFAULT_SERVICES: ServiceRecord[] = [
  {
    id: "haircut-18",
    name: "Haircut (18+)",
    price: 25,
    duration: 45,
    description: "Classic cut for adults 18 and over.",
    category: "Main Services",
    active: true,
    barber_ids: ["m-blendz"],
    sort_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "haircut-beard",
    name: "Haircut & Beard",
    price: 30,
    duration: 50,
    description: "Haircut with beard trim and shape.",
    category: "Main Services",
    active: true,
    barber_ids: ["m-blendz"],
    sort_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "shape-up",
    name: "Shape Up",
    price: 15,
    duration: 20,
    description: "Line-up and shape around the edges.",
    category: "Additional Services",
    active: true,
    barber_ids: ["m-blendz"],
    sort_order: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "haircut-under-18",
    name: "Haircut (under 18s)",
    price: 20,
    duration: 40,
    description: "Haircut for under 18s.",
    category: "Other",
    active: true,
    barber_ids: ["m-blendz"],
    sort_order: 4,
    created_at: new Date().toISOString(),
  },
];
